### ISSUE TITLE
Allow to easily configure loggers

### ISSUE THREAD

**Issue by utybo** [utybo/Tegral#9]
Following #8, make it easy to configure loggers, their level, etc.

**Comment by utybo** [comment]
Here's an example of the planned syntax:

```toml
[tegral.logging]
level = "DEBUG"

[tegral.logging.loggers."my.example.logger"]
level = "INFO"
```
