### ISSUE TITLE
Support for Kotlin Uuid

### ISSUE THREAD

**Issue by perracodex** [utybo/Tegral#98]
Kotlin 2.0.20 has [introduced](https://kotlinlang.org/docs/whatsnew2020.html#support-for-uuids-in-the-common-kotlin-standard-library) Uuid support in the standard library.
In addition, kotlinx.serialization also has been updated in version 1.7.2 to handle the Uuid type.

Issue:
When using the Uuid type with Tegral OpenAPI, it generates the next output:

```
"id": {
  "mostSignificantBits": 0,
  "leastSignificantBits": 0
}
```

Instead, of the expected:

```
id:   
  type: "string"   
  format: "uuid"
```

Sample usage:

```
"id" pathParameter {
        description = "Path parameter"
        schema<Uuid>()
 }
```

**Comment by utybo** [comment]
Tegral OpenAPI uses [Swagger Core](https://github.com/swagger-api/swagger-core) under the hood, which in turn uses Jackson. Since Kotlin's UUID is not supported at all in Jackson ([it's not even supported in the Kotlin-specific module apparently](https://github.com/FasterXML/jackson-module-kotlin)), I think the best way to do this is:

- Create a custom serializer for Kotlin's UUID (likely to be very similar to Jackson's handling for [Java's UUID](https://github.com/FasterXML/jackson-databind/blob/ef871bb3a5765972ee9c5528a079b37cc3c25e3b/src/main/java/com/fasterxml/jackson/databind/ser/std/UUIDSerializer.java))
- Add it in the mapper used internally by Swagger Core. Not 100% sure how this is done but it shouldn't be too bad.

**Comment by perracodex** [comment]
Does the Tegral OpenAPI have access to the final generated OpenApi file? If so, before serving it, it could do a workaround by searching in the schema for `Uuid` and changing it before it is served. 

So:
```
    Uuid:
      type: "object"
      properties:
        mostSignificantBits:
          type: "integer"
          format: "int64"
        leastSignificantBits:
          type: "integer"
          format: "int64"
```

should be replaced by:

```
    Uuid:
      type: "string"
      format: "uuid"
```
